### ISSUE TITLE
Keybindings as a component?

### ISSUE THREAD

**Issue by tmcw** [mapbox/react-keybinding#14]
Would this be clearer or better?

``` jsx
<Keybinding mapping={{'cmd+s': this.foobar}}>
</Keybinding>
```

This would allow us to use [react-side-effect](https://github.com/gaearon/react-side-effect) much like [react-document-title](https://github.com/gaearon/react-document-title) does.

Does this seem like a good use of react-side-effect @gaearon?

**Comment by gaearon** [comment]
Indeed, this is the use case I meant. (Assuming you want nested keybindings to override parent ones for the same combination.)

**Comment by gaearon** [comment]
Another upside is this being consumable from ES6 (and generally non-createClass) classes in 0.13.

**Comment by KyleAMathews** [comment]
I'm liking more and more putting everything into components. I was tripped up for a while seeing components as equaling fancy DOM elements so non-dom-emitting components felt weird. But since switching my mental model to one where components equal composable behaviors, it feels fine to do stuff like this or components that fetch data or stuff like @gaearon's react-document-title.

On the clarity question — I think it's much more clear vs. hiding things in mixins. I tend to forget that my mixins are even there whereas components + JSX make it very obvious what's happening.

**Comment by datapimp** [comment]
I also have come around to the `react-side-effect` approach to this after seeing @gaearon examples

LIke @KyleAMathews my mental model changed from thinking about components only as DOM emitting things.  The actual web components standard has a lot of custom tags you can use for simple AJAX requests and it seems to be a pretty nice UX for the developer.

**Comment by datapimp** [comment]
Is there anything I can do to help complete the work on the component branch?

**Comment by tmcw** [comment]
Ah, sorry - I have an application that already uses 1.x so I haven't had much time to work on 2.x, but I really should, especially when we're switching to 0.13.
- Made a PR: https://github.com/mapbox/react-keybinding/pull/15 with checklist
- Added you as a contributor

**Comment by tmcw** [comment]
Closing: [react-hotkeys](https://github.com/chrisui/react-hotkeys) implements this approach. For the time being we'll stick to the existing api in react-keybinding.
